---
title: "Aplicação do TRE"
output: 
  html_notebook: 
    number_sections: yes
    toc: yes
---

# Pré-configurações

```{r, message=FALSE, warning=FALSE}
# Limpando área
rm(list = ls())

# Carregando pacotes necessários
easypackages::libraries(
  c("dplyr", "tidyverse", "ggfortify", "lubridate", "modelr", "fs")
  )

# Carregando scripts necessários
source("../R/network-dists.R")
source("../R/get-aws-neighborhood.R")
source("../R/daily_summary.R")
source("../R/select-data-SRT.R")
source("../R/overlap.R")

source("../R/check_aws_srt_feasibility.R")
source("../R/add_intervals.R")
source("../R/utils.R")
source("../R/spatial_regression_test-v2.R")

```

# Parâmetros

```{r}
M = 20
interval_size = 60
aws_target = "A882"
aws_variable = "tavg" 
perc_ref = 50 
r2_threshold = 0.55  
```


# Dados necessários

Metadados das EMAs

```{r}
meta_data <- rio::import("../output/summary_80.rds") %>% as_tibble
meta_data
```

tabela de vizinhança entre as EMAs.

```{r}
neigh <- get_aws_neighborhood(meta_data, outfile = NULL)
neigh
```



Dados diários 

```{r}
daily_data <- rio::import("../output/s08_data_sel.rds") %>% 
  # daily averages
  daily_summary(col_vars = aws_variable)
daily_data
```


Dados diários com intervalo e em formato amplo.

```{r}
interval_data <- daily_data %>%
  add_intervals(interval_size = interval_size) #%>%
  #spread(site, !!aws_variable)
interval_data
```


```{r}
interval_availab <- interval_data %>% #tail()
  group_by(int, site) %>%
  #summarise(N = n())
  summarise(start_int = min(date),
            end_int = max(date),
            #tot_days = n(),
            tot_valid = sum(!is.na(tavg)),
            perc_valid = (tot_valid/n()) * 100
            ) %>%
  ungroup()
interval_availab
```

  

Seleção de dados para aplicação do TRE à todas EMAs.

Códigos de todas EMAs:
```{r}
#unique(interval_data$site)
(targets <- unique(interval_data$site))
```

Dados de todas EMAs:

```{r}

tre_data <- map_df(
  targets,
  ~select_data_SRT(
    data = interval_data,
    neighbors = neigh,
    aws_code = .,
    m = M
  )
) %>%  arrange_vars(c("target" = 1))
#filter(tre_data, target == "A872") %>% View()

# sort(unique(tre_data$target))
# sort(unique(tre_data$site))

# todos sites tem 10 EMAs vizinhas
tre_data %>%
  group_by(target) %>%
  summarise(nsites_difere = n_distinct(site)) %>%
  distinct(nsites_difere) 
```

Combinações possíveis entre pares de EMAs.

```{r}
aws_combs <- tre_data %>%
  select(site) %>%
  distinct() %>%
  pull() %>%
  combn(m = 2) %>%
  t() %>%
  as_tibble() %>%
  set_names(c("aws1", "aws2"))
aws_combs

aws_combs %>% group_by(aws1) %>% tally()
```



```{r}

# tabela de ref para looping
tab_int_site <- tre_data %>%
  distinct(site, int) 

# para encontrar casos baseados na linha
tab_int_site %>%
  rowid_to_column() %>%
  filter(site == "A852", int == 37)

```
 
 
```{r}
result_srt <- map_df(
  1:nrow(tab_int_site),
  #c(1, nrow(tab_int_site)),
  function(irow) {
    #  irow = 200
    # ema alvo
    (itarget <- tab_int_site[irow, "site"][[1]])
    # invervalo
    (iint <- tab_int_site[irow, "int"][[1]])
    
    # EMAs vizinhas por proximidade -------------------------------------------
    aws_ord <- stations_neighbors(neigh, aws_id = itarget, M = 20)

    # Dados---------------------------------------------------------------------
    data_int_wide <- tre_data %>%
      # dados da target
      filter(., target == itarget, int == iint) %>%
      # formato amplo
      spread(site, !!aws_variable) %>%
      # ordena cols por proximidade
      select(target:int, one_of(aws_ord))
    
    # Combinações da alvo com as vizinhas no intervalo--------------------------
    site_colnames_data <- sort(stringr::str_extract(names(data_int_wide), "^A[0-9]{3}"))
    target_combs_int <- aws_combs %>%
      # filtra a alvo e as vizinhas que estão nos dados wide
      filter(aws1 == itarget) %>%
      filter(aws2 %in% site_colnames_data) %>%
      mutate(overlap = overlap_combs(data_int_wide, .)/interval_size * 100) 
      
    # seleção das EMAs que tenham 50% de sobreposição com a target -------------
    target_combs_sel <- filter(target_combs_int, overlap >= perc_ref)
    # codigos das EMAs que atendem ao critério de sobreposição
    sites_sel <- select(target_combs_sel, -overlap) %>% t() %>% c() %>% unique()
    
    # dados das emas com sobreposicao >= 50% com a alvo e renomeia a alvo para x
    data_int_wide_sel <- data_int_wide %>%
      select(target:int, one_of(sites_sel)) %>%
      rename("x" = itarget)
    
    out_srt <- spatial_regression_test(data_int_wide_sel, R2_THRESHOLD = R2_THRESHOLD, f = f) %>%
      mutate(site = itarget, int = iint) %>%
      arrange_vars(c("site" = 1, "int" = 2)) %>%
      as_tibble()
    
    return(out_srt)
  }
)

result_srt
```
 
 