---
title: "Aplicação do TRE"
output: 
  html_notebook: 
    number_sections: yes
    toc: yes
---

# Pré-configurações

```{r, message=FALSE, warning=FALSE}
# Limpando área
rm(list = ls())

# Carregando pacotes necessários
easypackages::libraries(
  c("dplyr", "tidyverse", "ggfortify", "lubridate", "modelr", "fs")
  )

# Carregando scripts necessários
source("../R/network-dists.R")
source("../R/get-aws-neighborhood.R")
source("../R/select-data-SRT.R")
source("../R/utils.R")
source("../R/spatial_regression_test.R")
```


# Dados necessários
```{r}
check_disp_int_inmet_ok <- rio::import("../output/check_disp_int_inmet_ok.RDS")
check_disp_int_inmet_ok
```

```{r}
daily_data <- rio::import("../output/tar-data-inmet-2008-2016-daily-interval60.RDS")
daily_data
```

# Aplicação do TRE

Seleção dos dados diários.

```{r}
aws_int <- 27 # intervalo teste

#aws_target <- "A882"
aws_target <- 'A802' #'caso ideal' do meu script
#aws_target <- 'A801' #'caso não ideal, e corrigivel' do meu script

check_disp_int_target <-
  filter(check_disp_int_inmet_ok, target == aws_target) %>%
  unnest()

neighbors_o <- c(aws_target, unique(check_disp_int_target$neighbors_checked))

daily_data_wide_target <-
  daily_data %>%
  dplyr::filter(
    site %in% neighbors_o,
    int %in% unique(check_disp_int_target$int)
  ) %>%
  tidyr::spread(site, variable) %>%
  dplyr::select(date, int, one_of(neighbors_o)) %>%
  rename("x" = aws_target) %>%
  dplyr::filter(int == aws_int) %>%
  dplyr::mutate(ema = aws_target) %>%
  dplyr::select(ema, int, date, x, everything())
daily_data_wide_target
```



```{r}
spatial_regression_test(
  DAYLE_DATA_WIDE = daily_data_wide_target,
  HAVE_VALID_DATA = TRUE,
  R2_THRESHOLD = 0.55,
  f = 3)
```


```{r}
# para cada ref 
#      roda teste espacial

```


<!-- Dados estruturados com formato sililar ao do exemplo de aplicação do método. O formato dos dados é com a data na 1ª coluna, a EMA de referência na 2ª coluna e as EMAs vizinhas nas demais colunas. -->

